# Generated by Django 3.1.7 on 2021-02-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20210226_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageUrl',
        ),
    ]
