# Generated by Django 3.1.7 on 2021-02-27 11:19

from django.db import migrations, models
import django.db.models.deletion
import instagram.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_remove_post_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=instagram.models.post_images_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='instagram.post')),
            ],
        ),
    ]
