# Generated by Django 3.1.7 on 2021-02-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0008_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='followed_user_id',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='followed_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='followed_users', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='follower',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='auth.user'),
            preserve_default=False,
        ),
    ]
