# Generated by Django 3.1.7 on 2021-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_auto_20210307_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
